#!/usr/bin/env bash
# ============================================================
# LINE Harness 手動デプロイ runbook（create-line-harness 相当）
#
#   bash scripts-local/deploy.sh
#
# 前提:
#   - npx wrangler login 済み（このアカウントに deploy される）
#   - setup.local.env を埋めてある（LINE 5項目 + PROJECT）
#   - pnpm install 済み
#
# 冪等性: 何度実行しても安全。
#   D1 / R2 / Pages は「既存ならスキップ」、スキーマは benign error 無視、
#   line_accounts は ON CONFLICT で upsert、API_KEY は state に固定保存。
# ============================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

ENV_FILE="$ROOT/setup.local.env"
STATE_FILE="$ROOT/scripts-local/.deploy-state.env"
# 親プロジェクトの .mcp.json（このリポを clone した1つ上）= Claude が読む実設定
PARENT_MCP="$(cd "$ROOT/.." && pwd)/.mcp.json"

WR() { npx --no-install wrangler "$@"; }

log()  { printf '\n\033[1;36m▶ %s\033[0m\n' "$*"; }
ok()   { printf '\033[1;32m✔ %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m! %s\033[0m\n' "$*"; }

# ---- load env + state ----
[ -f "$ENV_FILE" ] || { echo "ERROR: $ENV_FILE がありません。setup.local.env.example をコピーして埋めてください。"; exit 1; }
set -a; . "$ENV_FILE"; [ -f "$STATE_FILE" ] && . "$STATE_FILE"; set +a

req() { eval "v=\${$1:-}"; [ -n "$v" ] || { echo "ERROR: $1 が空です（setup.local.env を確認）"; exit 1; }; }
for k in PROJECT LINE_CHANNEL_ID LINE_CHANNEL_ACCESS_TOKEN LINE_CHANNEL_SECRET LINE_LOGIN_CHANNEL_ID LIFF_ID; do req "$k"; done

# ---- state persistence ----
API_KEY="${API_KEY:-}"
D1_ID="${D1_ID:-}"
WORKER_URL="${WORKER_URL:-}"
ADMIN_PROJECT="${ADMIN_PROJECT:-}"
ADMIN_URL="${ADMIN_URL:-}"
BOT_BASIC_ID="${BOT_BASIC_ID:-}"

persist() {
  mkdir -p "$ROOT/scripts-local"
  {
    echo "# generated by deploy.sh — do not commit"
    echo "API_KEY=$API_KEY"
    echo "D1_ID=$D1_ID"
    echo "WORKER_URL=$WORKER_URL"
    echo "ADMIN_PROJECT=$ADMIN_PROJECT"
    echo "ADMIN_URL=$ADMIN_URL"
    echo "BOT_BASIC_ID=$BOT_BASIC_ID"
  } > "$STATE_FILE"
  chmod 600 "$STATE_FILE"
}

R2_BUCKET="${PROJECT}-images"
WORKER_DIR="$ROOT/apps/worker"
WEB_DIR="$ROOT/apps/web"

# ============================================================
log "Step 0. 環境確認"
WR whoami | grep -i "logged in" || { echo "wrangler 未ログイン。'npx wrangler login' を実行してください。"; exit 1; }
[ -z "$API_KEY" ] && API_KEY="$(openssl rand -hex 32)"
persist
ok "PROJECT=$PROJECT / R2=$R2_BUCKET / API_KEY=${API_KEY:0:8}…"

# ============================================================
log "Step 1. D1 データベース"
if [ -z "$D1_ID" ]; then
  EXIST_ID="$(WR d1 list --json 2>/dev/null | jq -r --arg n "$PROJECT" '.[] | select(.name==$n) | .uuid' | head -1)"
  if [ -n "$EXIST_ID" ] && [ "$EXIST_ID" != "null" ]; then
    D1_ID="$EXIST_ID"; ok "既存 D1 を使用: $D1_ID"
  else
    OUT="$(WR d1 create "$PROJECT" 2>&1)"; echo "$OUT"
    D1_ID="$(printf '%s' "$OUT" | grep -oiE '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' | head -1)"
    [ -n "$D1_ID" ] || { echo "D1 ID をパースできませんでした"; exit 1; }
    ok "D1 作成: $D1_ID"
  fi
  persist
else
  ok "D1: 既知（$D1_ID）"
fi

log "Step 2. スキーマ適用（bootstrap + 差分 migration）"
d1exec() { WR d1 execute "$PROJECT" --remote --file "$1" 2>&1 | tail -3 || true; }
echo "  - bootstrap.sql"; d1exec "$ROOT/packages/db/bootstrap.sql"
PENDING="$(node -e '
const fs=require("fs"),p=require("path");
const dir=p.join(process.cwd(),"packages/db/migrations");
const meta=JSON.parse(fs.readFileSync("packages/db/bootstrap-meta.json","utf8"));
const inc=new Set(meta.includedMigrations||[]);
const files=fs.readdirSync(dir).filter(f=>f.endsWith(".sql")).sort();
console.log(files.filter(f=>!inc.has(f)).join("\n"));
')"
if [ -n "$PENDING" ]; then
  while IFS= read -r m; do [ -z "$m" ] && continue; echo "  - migration $m"; d1exec "$ROOT/packages/db/migrations/$m"; done <<< "$PENDING"
fi
VERIFY="$(WR d1 execute "$PROJECT" --remote --command "SELECT name FROM sqlite_master WHERE type='table' AND name='line_accounts'" 2>&1 || true)"
echo "$VERIFY" | grep -q line_accounts || { echo "ERROR: line_accounts テーブルが見つかりません"; exit 1; }
ok "スキーマ適用完了"

# ============================================================
log "Step 3. R2 バケット"
if WR r2 bucket list 2>/dev/null | grep -q "name:.*$R2_BUCKET"; then
  ok "R2: 既存（$R2_BUCKET）"
else
  WR r2 bucket create "$R2_BUCKET" 2>&1 | tail -2 || true; ok "R2 作成: $R2_BUCKET"
fi

# ============================================================
log "Step 4. Bot Basic ID 取得（任意）"
if [ -z "$BOT_BASIC_ID" ]; then
  BOT_BASIC_ID="$(curl -s -H "Authorization: Bearer $LINE_CHANNEL_ACCESS_TOKEN" https://api.line.me/v2/bot/info | jq -r '.basicId // empty' || true)"
  persist
fi
ok "Bot Basic ID: ${BOT_BASIC_ID:-(未取得)}"

# ============================================================
log "Step 5. Worker ビルド & デプロイ"
ACCOUNT_ID="$(WR whoami 2>/dev/null | grep -oiE '[0-9a-f]{32}' | head -1)"
[ -n "$ACCOUNT_ID" ] || { echo "Account ID を取得できませんでした"; exit 1; }

# deploy 用 wrangler.toml（CLI と同一内容）
cat > "$WORKER_DIR/wrangler.toml" <<TOML
name = "$PROJECT"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
account_id = "$ACCOUNT_ID"

[assets]
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "$PROJECT"
database_id = "$D1_ID"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "$R2_BUCKET"

[triggers]
crons = ["*/5 * * * *"]
TOML

# LIFF クライアント用ビルド変数
printf 'VITE_LIFF_ID=%s\nVITE_BOT_BASIC_ID=%s\n' "$LIFF_ID" "$BOT_BASIC_ID" > "$WORKER_DIR/.env"

echo "  - workspace deps build"
pnpm -r --filter ./packages/shared --filter ./packages/line-sdk --filter ./packages/db --filter ./packages/update-engine build
echo "  - vite build"
( cd "$WORKER_DIR" && npx --no-install vite build )
echo "  - wrangler deploy"
DOUT="$( cd "$WORKER_DIR" && WR deploy 2>&1 )"; echo "$DOUT" | tail -8
WORKER_URL="$(printf '%s' "$DOUT" | grep -oiE 'https://[^ ]+\.workers\.dev' | head -1)"
[ -n "$WORKER_URL" ] || { echo "Worker URL をパースできませんでした"; exit 1; }
persist; ok "Worker: $WORKER_URL"

# ============================================================
log "Step 6. Worker シークレット投入"
jq -n \
  --arg t "$LINE_CHANNEL_ACCESS_TOKEN" --arg s "$LINE_CHANNEL_SECRET" \
  --arg l "$LINE_LOGIN_CHANNEL_ID" --arg u "https://liff.line.me/$LIFF_ID" --arg k "$API_KEY" \
  '{LINE_CHANNEL_ACCESS_TOKEN:$t, LINE_CHANNEL_SECRET:$s, LINE_LOGIN_CHANNEL_ID:$l, LIFF_URL:$u, API_KEY:$k}' \
  | WR secret bulk --name "$PROJECT" 2>&1 | tail -3
ok "シークレット設定完了"

# ============================================================
log "Step 7. line_accounts に登録（upsert）"
SQLF="$(mktemp -t clh-acct.XXXXXX.sql)"; chmod 600 "$SQLF"
trap 'rm -f "$SQLF"' EXIT
JST="$(node -e 'console.log(new Date(Date.now()+9*3600e3).toISOString().slice(0,-1)+"+09:00")')"
ID="$(node -e 'console.log(require("crypto").randomUUID())')"
qq() { printf "%s" "$1" | sed "s/'/''/g"; }
cat > "$SQLF" <<SQL
INSERT INTO line_accounts (id, channel_id, name, channel_access_token, channel_secret, is_active, created_at, updated_at)
VALUES ('$(qq "$ID")', '$(qq "$LINE_CHANNEL_ID")', 'LINE Harness', '$(qq "$LINE_CHANNEL_ACCESS_TOKEN")', '$(qq "$LINE_CHANNEL_SECRET")', 1, '$(qq "$JST")', '$(qq "$JST")')
ON CONFLICT(channel_id) DO UPDATE SET
  channel_access_token = excluded.channel_access_token,
  channel_secret = excluded.channel_secret,
  updated_at = '$(qq "$JST")';
SQL
WR d1 execute "$PROJECT" --remote --file "$SQLF" 2>&1 | tail -3
rm -f "$SQLF"
# login_channel_id は best-effort（古いスキーマには列が無い場合あり）
SQLF2="$(mktemp -t clh-login.XXXXXX.sql)"; chmod 600 "$SQLF2"
printf "UPDATE line_accounts SET login_channel_id = '%s' WHERE channel_id = '%s';\n" "$(qq "$LINE_LOGIN_CHANNEL_ID")" "$(qq "$LINE_CHANNEL_ID")" > "$SQLF2"
WR d1 execute "$PROJECT" --remote --file "$SQLF2" 2>&1 | tail -2 || warn "login_channel_id 更新はスキップ（後で管理画面から設定可）"
rm -f "$SQLF2"
ok "LINE アカウント登録完了"

# ============================================================
log "Step 8. 管理画面（Pages）ビルド & デプロイ"
[ -z "$ADMIN_PROJECT" ] && ADMIN_PROJECT="${PROJECT}-admin-${API_KEY:0:8}"
printf 'NEXT_PUBLIC_API_URL=%s\n' "$WORKER_URL" > "$WEB_DIR/.env.production"
echo "  - next build"
( cd "$WEB_DIR" && pnpm run build )
WR pages project create "$ADMIN_PROJECT" --production-branch main 2>&1 | tail -2 || true
echo "  - pages deploy"
( cd "$WEB_DIR" && WR pages deploy out --project-name "$ADMIN_PROJECT" --commit-dirty=true 2>&1 | tail -6 )
PURL="$(WR pages project list 2>/dev/null | grep -oE "[A-Za-z0-9.-]+\.pages\.dev" | grep "$ADMIN_PROJECT" | head -1 || true)"
ADMIN_URL="https://${PURL:-$ADMIN_PROJECT.pages.dev}"
persist; ok "Admin: $ADMIN_URL"

# ============================================================
log "Step 9. 管理画面の認証設定（クロスサイト Cookie / CORS）"
jq -n --arg o "$ADMIN_URL" --arg w "$WORKER_URL" \
  '{ADMIN_ORIGIN:$o, ADMIN_ALLOW_CROSS_SITE:"true", WORKER_URL:$w}' \
  | WR secret bulk --name "$PROJECT" 2>&1 | tail -3
ok "認証設定完了"

# ============================================================
log "Step 10. 最終 wrangler.toml 生成 & 再デプロイ"
cat > "$WORKER_DIR/wrangler.toml" <<TOML
# Generated by scripts-local/deploy.sh. Safe to overwrite on future runs.
name = "$PROJECT"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
account_id = "$ACCOUNT_ID"

[assets]
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "$PROJECT"
database_id = "$D1_ID"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "$R2_BUCKET"

[triggers]
crons = ["*/5 * * * *", "0 */6 * * *"]

[vars]
WORKER_NAME = "$PROJECT"
ADMIN_PAGES_PROJECT = "$ADMIN_PROJECT"
LIFF_PAGES_PROJECT = "${PROJECT}-liff"
D1_DATABASE_ID = "$D1_ID"
WORKER_PUBLIC_URL = "$WORKER_URL"
ADMIN_PUBLIC_URL = "$ADMIN_URL"
LIFF_PUBLIC_URL = "$WORKER_URL"
CF_ACCOUNT_ID = "$ACCOUNT_ID"
MANIFEST_URL = "https://github.com/Shudesu/line-harness-oss/releases/latest/download/release-manifest.json"
TOML
( cd "$WORKER_DIR" && npx --no-install vite build >/dev/null 2>&1 && WR deploy 2>&1 | tail -4 )
ok "再デプロイ完了"

# ============================================================
log "Step 11. .mcp.json 更新（$PARENT_MCP）"
node -e '
const fs=require("fs");
const path=process.argv[1], url=process.argv[2], key=process.argv[3];
let cfg={}; try{cfg=JSON.parse(fs.readFileSync(path,"utf8"))}catch{}
cfg.mcpServers=cfg.mcpServers||{};
cfg.mcpServers["line-harness"]={command:"npx",args:["-y","@line-harness/mcp-server@latest"],env:{LINE_HARNESS_API_URL:url,LINE_HARNESS_API_KEY:key}};
fs.writeFileSync(path, JSON.stringify(cfg,null,2)+"\n");
console.log("updated "+path);
' "$PARENT_MCP" "$WORKER_URL" "$API_KEY"
ok ".mcp.json 更新完了"

# ============================================================
cat <<DONE

============================================================
✅ デプロイ完了
------------------------------------------------------------
 Worker URL : $WORKER_URL
 Admin URL  : $ADMIN_URL   （ログイン: API_KEY = ${API_KEY:0:8}…）
 D1         : $PROJECT ($D1_ID)
 R2         : $R2_BUCKET
 MCP        : $PARENT_MCP を更新（Claude Code 再起動で反映）

 残り手動作業（LINE コンソール）:
  1. Messaging API → Webhook URL を設定:
        $WORKER_URL/webhook
     （Webhook 利用を ON / 応答メッセージ等は任意）
  2. LIFF → エンドポイント URL を Worker に変更:
        $WORKER_URL
     LIFF を「公開」状態にする
  3. 管理画面 $ADMIN_URL に API_KEY でログイン
============================================================
DONE
